"""
Run this once to seed 10 sample donors into the database.
    python seed_donors.py
"""

from database import init_db, add_donor

init_db()

DONORS = [
    {
        "name": "Arjun Mehta",
        "age": 28,
        "gender": "Male",
        "blood_type": "A+",
        "phone": "9812345601",
        "email": "arjun.mehta@email.com",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "lat": 19.0760,
        "lon": 72.8777,
        "organs": ["Blood", "Kidney"],
    },
    {
        "name": "Priya Nair",
        "age": 32,
        "gender": "Female",
        "blood_type": "B+",
        "phone": "9812345602",
        "email": "priya.nair@email.com",
        "city": "Kochi",
        "state": "Kerala",
        "country": "India",
        "lat": 9.9312,
        "lon": 76.2673,
        "organs": ["Blood", "Cornea"],
    },
    {
        "name": "Rohit Sharma",
        "age": 25,
        "gender": "Male",
        "blood_type": "O+",
        "phone": "9812345603",
        "email": "rohit.sharma@email.com",
        "city": "Delhi",
        "state": "Delhi",
        "country": "India",
        "lat": 28.6139,
        "lon": 77.2090,
        "organs": ["Blood", "Kidney", "Liver"],
    },
    {
        "name": "Sneha Reddy",
        "age": 29,
        "gender": "Female",
        "blood_type": "O-",
        "phone": "9812345604",
        "email": "sneha.reddy@email.com",
        "city": "Hyderabad",
        "state": "Telangana",
        "country": "India",
        "lat": 17.3850,
        "lon": 78.4867,
        "organs": ["Blood", "Bone Marrow"],
    },
    {
        "name": "Vikram Singh",
        "age": 35,
        "gender": "Male",
        "blood_type": "AB+",
        "phone": "9812345605",
        "email": "vikram.singh@email.com",
        "city": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "lat": 26.9124,
        "lon": 75.7873,
        "organs": ["Blood", "Kidney", "Pancreas"],
    },
    {
        "name": "Kavya Iyer",
        "age": 27,
        "gender": "Female",
        "blood_type": "A-",
        "phone": "9812345606",
        "email": "kavya.iyer@email.com",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "country": "India",
        "lat": 13.0827,
        "lon": 80.2707,
        "organs": ["Blood", "Cornea", "Skin"],
    },
    {
        "name": "Amit Patel",
        "age": 40,
        "gender": "Male",
        "blood_type": "B-",
        "phone": "9812345607",
        "email": "amit.patel@email.com",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "country": "India",
        "lat": 23.0225,
        "lon": 72.5714,
        "organs": ["Blood", "Kidney", "Liver"],
    },
    {
        "name": "Divya Krishnan",
        "age": 31,
        "gender": "Female",
        "blood_type": "AB-",
        "phone": "9812345608",
        "email": "divya.krishnan@email.com",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "lat": 12.9716,
        "lon": 77.5946,
        "organs": ["Blood", "Bone Marrow", "Cornea"],
    },
    {
        "name": "Suresh Kumar",
        "age": 38,
        "gender": "Male",
        "blood_type": "O+",
        "phone": "9812345609",
        "email": "suresh.kumar@email.com",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "lat": 18.5204,
        "lon": 73.8567,
        "organs": ["Blood", "Kidney", "Heart", "Lung"],
    },
    {
        "name": "Ananya Das",
        "age": 24,
        "gender": "Female",
        "blood_type": "A+",
        "phone": "9812345610",
        "email": "ananya.das@email.com",
        "city": "Kolkata",
        "state": "West Bengal",
        "country": "India",
        "lat": 22.5726,
        "lon": 88.3639,
        "organs": ["Blood", "Skin", "Small Intestine"],
    },
]

if __name__ == "__main__":
    print("Seeding 10 donors...")
    for donor in DONORS:
        donor_id = add_donor(donor)
        print(f"  Added: {donor['name']} ({donor['blood_type']}) -> ID #{donor_id}")
    print("\nDone! 10 donors added successfully.")
